kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: CICD_project
  template:
    metadata:
        name: testpod8
        labels:
          env: CICD_project
    spec:
      containers:
        - name: c00
          image: ajaykumar143/ajay123:cicd
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
 name: demoservice
spec: 
 ports:
  - port: 8080
    targetPort: 8080
 selector:
   env: CICD_project